updated img tags using next/image library, fixed compound and earn pa…
Snowball-Finance/app-v2 pull request #260
Opened 2021-09-22 04:53 UTC by prodvdjin

…ir icons loading issue

2021-09-22 17:23 UTC, Jonasslv requested changes, later dismissed
Icons on S4D Stablevault broke with this changes.
Also on mobile the S4D Pair icons in Compound & Earn page need to adjust the shadow.

![Captura de tela de 2021-09-22 14-17-57](https://user-images.githubusercontent.com/20801365/134391360-f2fcb960-d791-4339-958c-72e980b35f8f.png)
![Captura de tela de 2021-09-22 14-18-36](https://user-images.githubusercontent.com/20801365/134391362-74f60c05-aad0-45f6-963f-ee062625d579.png)
![Captura de tela de 2021-09-22 14-18-43](https://user-images.githubusercontent.com/20801365/134391364-55583709-0a55-471a-9199-e4f857aa222d.png)

2021-09-22 19:41 UTC, prodvdjin commented
@Jonasslv Handled above feedback

2021-09-23 01:22 UTC, Jonasslv commented
LGTM Thanks for the PR @prodvdjin, really great to have some contributions.

2021-09-23 01:22 UTC, Jonasslv approved these changes

2021-09-23 01:23 UTC, merged