Feat/claim withdraw
Snowball-Finance/app-v2 pull request #263
Opened 2021-09-22 13:19 UTC by InvokerMaster

https://app.asana.com/0/1200430190389164/1200977220251752

# Description

Call claiming when Withdraw

2021-09-22 14:30 UTC, InvokerMaster commented
Currently it is just calling claim function
And there is another pull request
https://github.com/Snowball-Finance/app-v2/pull/264/files

And this is containing if the claimable amount is greater than 0

2021-09-22 16:15 UTC, Jonasslv requested changes, later dismissed
We will need to implement one extra step on the Withdraw Dialog for claiming, it will now be three steps, the first one for claiming and then the two withdraws.

Be aware that I rebased your PR with latest dev branch, please update your local repository.

2021-09-28 15:32 UTC, Jonasslv commented
LGTM

2021-09-28 15:32 UTC, Jonasslv approved these changes

2021-09-28 15:32 UTC, merged