Bug/pools order
Snowball-Finance/app-v2 pull request #347
Opened 2021-10-29 12:42 UTC by Sanjeev1308

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201280901526823

2021-10-29 17:18 UTC, prodvdc approved these changes

2021-10-29 17:24 UTC, saito-sv commented
Looks like the issues still there. Also, it seems that the filter of the user pools bring the loading time back to where it was before.

2021-10-29 17:25 UTC, saito-sv requested changes
Looks like the issues still there. Also, it seems that the filter of the user pools bring the loading time back to where it was before.

2021-11-18 21:39 UTC, saito-sv approved these changes
LGTM

2021-11-24 17:54 UTC, merged