Feat/deposit UI
Snowball-Finance/app-v2 pull request #348
Opened 2021-10-29 19:10 UTC by mohsenParvar

2021-10-29 19:30 UTC, prodvdjin commented
@mohsenParvar Mobile view needs some stuff for UX
![image](https://user-images.githubusercontent.com/78897434/139491709-0ce433b7-7fa4-4273-84c6-505dddc38589.png)

2021-10-29 19:32 UTC, prodvdjin commented
@mohsenParvar on stable vault, it has an issue when selecting other token from combo box.
![image](https://user-images.githubusercontent.com/78897434/139491932-59caf633-d66b-4d0c-ba5b-27d61bed395c.png)

2021-11-02 21:03 UTC, saito-sv requested changes

2021-11-02 21:03 UTC, saito-sv commented on components/Icons/ArrowDownIcon/index.js
> +  root: {
Please remove or add a description.

2021-11-04 18:54 UTC, Jonasslv submitted a review, later dismissed
Looks like vercel is having problems deploying your last commit. Can you look into it so I can test it properly?

2021-11-05 21:03 UTC, saito-sv submitted a review, later dismissed

2021-11-05 21:03 UTC, saito-sv commented on parts/Compound/CompoundDialogs/CompoundInfo/index.js
> +
remove unnecessary extra spaces.

2021-11-05 21:03 UTC, saito-sv commented on parts/Compound/CompoundDialogs/index.js
> +
remove extra spacing

2021-12-02 02:56 UTC, Jonasslv reviewed
I'm not very confident about the token0balance, token1balance and AVAXBalance autorefresh, we should test some edge cases:
- Get AVAX, token0 and token1 from TJ/Pangolin on a tab, try to deposit on snowball on the other tab without hard refreshing.

2021-12-02 02:56 UTC, Jonasslv commented on parts/Compound/CompoundListItem/DetailItem/index.js
> +        This pool is deprecated and don{`'`}t receive rewards anymore, please withdraw from it.
it was right before

2021-12-02 02:56 UTC, Jonasslv commented on parts/Compound/CompoundDialogs/reducer.js
> +                newState.inputAmount = inputAmount > 1e-6 ? inputAmount : Number(inputAmount).toLocaleString('en-US', { maximumSignificantDigits: 18 })
needs a line break

2021-12-02 02:56 UTC, Jonasslv commented on contexts/compound-and-earn-context.js
> +  const deposit = async (item, amount, addressFromZapper, onlyGauge = false, isNativeAVAX = false) => {
We need to check if this function is not used elsewhere, because it's declaration changed

2021-12-02 02:58 UTC, Jonasslv commented
We should look for regressions too, the base of this PR is very old

2021-12-06 19:30 UTC, ghost commented
> I'm not very confident about the token0balance, token1balance and AVAXBalance autorefresh, we should test some edge cases:
> 
> * Get AVAX, token0 and token1 from TJ/Pangolin on a tab, try to deposit on snowball on the other tab without hard refreshing.

tested, seems to be working fine

2021-12-10 16:48 UTC, Jonasslv approved these changes
LGTM

2021-12-10 16:56 UTC, merged