matomo integration
Snowball-Finance/app-v2 pull request #375
Opened 2021-11-22 15:01 UTC by mohsenParvar

2021-11-23 03:49 UTC, saito-sv requested changes

2021-11-23 03:49 UTC, saito-sv commented on components/UI/Buttons/LinkButton/index.js
> +
remove extra space

2021-11-23 03:49 UTC, saito-sv commented on components/WalletModal/index.js
> +
remove extra space

2021-11-23 03:49 UTC, saito-sv commented on contexts/analytics.js
> +
remove extra space

2021-11-23 03:49 UTC, saito-sv commented on pages/_app.js
> +
remove extra spaces

2021-11-23 03:49 UTC, saito-sv commented on parts/Compound/CompoundDialogs/index.js
> +
remove unnecessary extra spaces

2021-11-23 03:49 UTC, saito-sv commented on parts/SubMenuTabs/index.js
> +
remove unnecessary space

2021-11-23 03:49 UTC, saito-sv commented on contexts/analytics.js
> +const instance = createInstance({
lets give this const a better name please

2021-11-23 03:49 UTC, saito-sv commented on contexts/analytics.js
> +const urlBase = '//analytics.snowapi.net/'
use .env file to hold this value

2021-11-24 17:49 UTC, Jonasslv commented
How is the state of this? How I can test it?

2021-11-25 00:38 UTC, saito-sv approved these changes
LGTM

2021-11-25 00:38 UTC, saito-sv commented
> How is the state of this? How I can test it?

@Jonasslv  should be good to go.

2021-11-25 00:44 UTC, merged