analytics improvements
Snowball-Finance/app-v2 pull request #397
Opened 2021-12-15 21:44 UTC by mohsenParvar

2021-12-17 19:09 UTC, Jonasslv commented
Can you check with @saito-sv why the live deployment failed for this PR? @mohsenParvar

2021-12-21 23:42 UTC, saito-sv commented on yarn.lock
> +  resolved "https://registry.npmjs.org/@ampproject/toolbox-core/-/toolbox-core-2.7.4.tgz"
this could be causing the build to failed.

2021-12-21 23:44 UTC, saito-sv requested changes
yarn.lock has too many changes unrelated to your task.

2021-12-22 00:04 UTC, saito-sv approved these changes
LGTM

2021-12-22 15:46 UTC, merged